import joblib, numpy as np, json, os
m = joblib.load("backend/models/phishing/logistic_regression_phishing_model.joblib")
v = joblib.load("backend/models/phishing/tfidf_phishing_vectorizer.joblib")
print("model      :", type(m).__name__)
print("vectorizer :", type(v).__name__)
print("vocab size :", len(v.vocabulary_))
print("coef shape :", np.asarray(m.coef_).shape)
print("intercept  :", np.asarray(m.intercept_).tolist())
print("classes    :", getattr(m, "classes_", None))
print("idf len    :", len(getattr(v, "idf_", [])))
print("ngram_range:", v.ngram_range, "| sublinear_tf:", v.sublinear_tf, "| norm:", v.norm)
print("lowercase  :", v.lowercase, "| stop_words:", type(v.stop_words).__name__)
